default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sportify_development

test:
  <<: *default
  database: sportify_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: sportify_production
  username: sportify
  password: <%= ENV['SPORTIFY_DATABASE_PASSWORD'] %>
